import { List } from 'immutable';

export const RAW_PREPARATIONS = new List([
	{
		author: 'Nicolas C.',
		className: 'list-item-folder',
		icon: 'talend-folder',
		id: '5bfeb80b7da2790bfb6f2001',
		name: 'djhssfskl jdsiald',
		type: 'folder',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-folder',
		icon: 'talend-folder',
		id: '5bfeb0cc7da2790bfb6f1ff9',
		name: 'test lalasjjkad',
		type: 'folder',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-folder',
		icon: 'talend-folder',
		id: '5bfeb0fd7da2790bfb6f1ffb',
		name: 'ghfhgj hg hj test',
		type: 'folder',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-folder',
		icon: 'talend-folder',
		id: '5bfeb1137da2790bfb6f1fff',
		name: 'ziohdsa dsdas',
		type: 'folder',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-preparation',
		datasetName: 'DQ WAVE LAB FILE 1',
		icon: 'talend-dataprep',
		id: '01edfa52-a8e8-40f8-9d7a-f8f90968a03c',
		name: 'iouc xyfguysxf',
		nbSteps: 4,
		type: 'preparation',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-preparation',
		datasetName: 'DQ WAVE LAB FILE 1',
		icon: 'talend-dataprep',
		id: '9158f69b-475b-4dd4-9855-ab98eb4f60ce',
		name: 'poiucfukxfs dsfs',
		nbSteps: 0,
		type: 'preparation',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-preparation',
		datasetName: 'DQ WAVE LAB FILE 1',
		icon: 'talend-dataprep',
		id: '7e54c8f2-fc61-4fee-ae60-7c450a7ff2d7',
		name: 'uhkjkjd sd',
		nbSteps: 0,
		type: 'preparation',
	},
	{
		author: 'Nicolas C.',
		className: 'list-item-preparation',
		datasetName: 'DQ WAVE LAB FILE 1',
		icon: 'talend-dataprep',
		id: '7560e05a-97dc-4773-bf3d-decb39c58160',
		name: 'dudsagi dua diougfod',
		nbSteps: 0,
		type: 'preparation',
	},
]);

export const SORTED_PREPARATIONS = [
	[
		{
			author: 'Nicolas C.',
			className: 'list-item-folder',
			icon: 'talend-folder',
			id: '5bfeb80b7da2790bfb6f2001',
			name: 'djhssfskl jdsiald',
			type: 'folder',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-folder',
			icon: 'talend-folder',
			id: '5bfeb0cc7da2790bfb6f1ff9',
			name: 'test lalasjjkad',
			type: 'folder',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-folder',
			icon: 'talend-folder',
			id: '5bfeb0fd7da2790bfb6f1ffb',
			name: 'ghfhgj hg hj test',
			type: 'folder',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-folder',
			icon: 'talend-folder',
			id: '5bfeb1137da2790bfb6f1fff',
			name: 'ziohdsa dsdas',
			type: 'folder',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-preparation',
			datasetName: 'DQ WAVE LAB FILE 1',
			icon: 'talend-dataprep',
			id: '01edfa52-a8e8-40f8-9d7a-f8f90968a03c',
			name: 'iouc xyfguysxf',
			nbSteps: 4,
			type: 'preparation',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-preparation',
			datasetName: 'DQ WAVE LAB FILE 1',
			icon: 'talend-dataprep',
			id: '9158f69b-475b-4dd4-9855-ab98eb4f60ce',
			name: 'poiucfukxfs dsfs',
			nbSteps: 0,
			type: 'preparation',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-preparation',
			datasetName: 'DQ WAVE LAB FILE 1',
			icon: 'talend-dataprep',
			id: '7e54c8f2-fc61-4fee-ae60-7c450a7ff2d7',
			name: 'uhkjkjd sd',
			nbSteps: 0,
			type: 'preparation',
		},
		{
			author: 'Nicolas C.',
			className: 'list-item-preparation',
			datasetName: 'DQ WAVE LAB FILE 1',
			icon: 'talend-dataprep',
			id: '7560e05a-97dc-4773-bf3d-decb39c58160',
			name: 'dudsagi dua diougfod',
			nbSteps: 0,
			type: 'preparation',
		},
	],
];
