/**
 * Export all your constants here
 * Ex: the actions types that are used by action creators and reducers
 */
const ALERT = 'ALERT';
const CANCEL_RENAME_PREPARATION = 'CANCEL_RENAME_PREPARATION';
const FETCH_PREPARATIONS = 'FETCH_PREPARATIONS';
const OPEN_ABOUT = 'OPEN_ABOUT';
const FETCH_VERSION = 'FETCH_VERSION';
const OPEN_FOLDER = 'OPEN_FOLDER';
const PREPARATION_DUPLICATE = 'PREPARATION_DUPLICATE';
const RENAME_PREPARATION = 'RENAME_PREPARATION';
const SET_TITLE_EDITION_MODE = 'SET_TITLE_EDITION_MODE';
const OPEN_PREPARATION_CREATOR = 'OPEN_PREPARATION_CREATOR';

export default {
	ALERT,
	CANCEL_RENAME_PREPARATION,
	FETCH_PREPARATIONS,
	OPEN_ABOUT,
	FETCH_VERSION,
	OPEN_FOLDER,
	PREPARATION_DUPLICATE,
	RENAME_PREPARATION,
	SET_TITLE_EDITION_MODE,
	OPEN_PREPARATION_CREATOR,
};

